version: "3.8"
services:
  db:
    image: postgres
    environment:
    POSTGRES_PASSWORD: mysecretpassword
    POSTGRES_USER: postgres
    POSTGRES_DB: podcasts
  volumes:
    - ./pgdata:/var/lib/docker/volumes
  ports:
    - "5432:5432"
