version: '3'
services:
  redis:
    image: redis:5.0.5
    ports:
      - '6379:6379'
  db:
    image: postgres
    ports:
      - 5432:5432
    # volumes:
    #   - /Users/nicksolante/Dont/GH/podcastBackend/app/volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_USER=postgres
      - POSTGRES_DB=podcasts
