version: "3"
services:
  db:
    image: postgres
    ports:
      - 5432:5432
    # volumes:
    #   - .:/app
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_USER=postgres
      - POSTGRES_DB=podcasts
